### ISSUE TITLE
Cluster API

### ISSUE THREAD

**Issue by nlamirault** [portefaix/portefaix-krm#92]
Provide KRM resources using [cluster-api](https://cluster-api.sigs.k8s.io/):

```[tasklist]
### Tasks
- [ ] https://github.com/portefaix/portefaix-krm/issues/245
- [ ] https://github.com/portefaix/portefaix-krm/issues/246
- [ ] https://github.com/portefaix/portefaix-krm/issues/247
- [ ] https://github.com/portefaix/portefaix-krm/issues/248
- [ ] https://github.com/portefaix/portefaix-krm/issues/249
- [ ] https://github.com/portefaix/portefaix-krm/issues/250
```

**Comment by nlamirault** [comment]
duplicate of https://github.com/portefaix/portefaix-kubernetes/issues/3981
